### ISSUE TITLE
Please remove the forked repo

### ISSUE THREAD

**Issue by HeySkidee** [NjauSamuel/React_Blog#1]
Hi, could you please remove the fork of my repository [cool-stuff-list](https://github.com/NjauSamuel/cool-stuff) from your profile? The code contains something that I don't want anyone to see, which is why I’ve also removed it from my profile for now.

**Comment by HeySkidee** [comment]
@NjauSamuel consider adding social links or an email to your GitHub profile bio so people can easily contact you

**Comment by NjauSamuel** [comment]
Done... Understood.
